# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            ASER
tagline:          'a large-scale weighted eventuality knowledge graph'
description:      ''
baseurl: '/ASER'
url: 'https://hkust-knowcomp.github.io/ASER/'

author:
  name:           'HKUST-KnowComp'
  url:            https://github.com/HKUST-KnowComp

paginate:         5

# Custom vars
version:          2.0

github:
  repo:           https://github.com/HKUST-KnowComp/ASER
